package main

import (
	"bufio"
	"fmt"
	"math/rand"
	"os"
	"strconv"
	"strings"
)

func main() {
	for i := 1; i < 5; i++ {

		n := rand.Intn(100) // Random number from 0 to 99
		reader := bufio.NewReader(os.Stdin)

		// User input
		fmt.Println("Guess attempt:", i)
		fmt.Print("Try to guess the number generated by the computer. Enter your guess: ")
		str1, err := reader.ReadString('\n')
		str1 = strings.TrimSuffix(str1, "\n")
		a, err := strconv.Atoi(str1)
		if err != nil {
			fmt.Println(err.Error())
			return
		}

		fmt.Println("The number generated by the computer is:", n)
		fmt.Println("Your guess was:", a)

		switch {
		case a < n:
			fmt.Println("Your guess is lower than the number.")
			fmt.Println("-------------------------------------")
		case a > n:
			fmt.Println("Your guess is higher than the number.")
			fmt.Println("-------------------------------------")
		default:
			fmt.Println("Congratulations! You guessed the correct number!")
			fmt.Println("-------------------------------------")
		}
	}
}
