# permissions for end users to edit secretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secretsync
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - secretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - secretsyncs/status
  verbs:
  - get
