package main

import (
	"fmt"
	"time"
)

func listenToChan(ch chan int) {
	for {
		i := <-ch
		fmt.Println("got ", i, " from channel")
		// simulate doing a lot of work
		time.Sleep(1 * time.Second)
	}
}

func main() {
	ch := make(chan int, 10)

	go listenToChan(ch)

	for i := 0; i <= 100; i++ {
		fmt.Println("sending", i, "to channel...")
		ch <- i
		fmt.Println("sent", i, "to channel...")
	}

	fmt.Println("Done")
	close(ch)
}

// ─λ go run main.go                                                                        0 (0.001s) < 11:52:31
// sending 0 to channel...
// sent 0 to channel...
// sending 1 to channel...
// sent 1 to channel...
// sending 2 to channel...
// sent 2 to channel...
// sending 3 to channel...
// sent 3 to channel...
// sending 4 to channel...
// sent 4 to channel...
// sending 5 to channel...
// sent 5 to channel...
// sending 6 to channel...
// sent 6 to channel...
// sending 7 to channel...
// sent 7 to channel...
// sending 8 to channel...
// sent 8 to channel...
// sending 9 to channel...
// sent 9 to channel...
// sending 10 to channel...
// got  0  from channel
// sent 10 to channel...
// sending 11 to channel...
// sent 11 to channel...
// sending 12 to channel...
// got  1  from channel
// got  2  from channel
// sent 12 to channel...
// sending 13 to channel...
// got  3  from channel
// sent 13 to channel...
// sending 14 to channel...
// got  4  from channel
// sent 14 to channel...
// sending 15 to channel...
// got  5  from channel
// sent 15 to channel...
// sending 16 to channel...
// got  6  from channel
// sent 16 to channel...
// sending 17 to channel...
// got  7  from channel
// sent 17 to channel...
// sending 18 to channel...
// got  8  from channel
// sent 18 to channel...
// sending 19 to channel...
// got  9  from channel
// sent 19 to channel...
// sending 20 to channel...
// got  10  from channel
// sent 20 to channel...
// sending 21 to channel...
// got  11  from channel
// sent 21 to channel...
// sending 22 to channel...
// got  12  from channel
// sent 22 to channel...
// sending 23 to channel...
// ^Csignal: interrupt
