apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Must be empty to match PVC with <unset> StorageClass
  hostPath:
    path: "/mnt/data/vault"  # Adjust this path based on your environment

