apiVersion: apps.example.com/v1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: secretsync
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  # TODO(user): Add fields here
  sourceNamespace: "default"
  destinationNamespaces: ["production", "development"]
  secretName: "example-secret"