SELECT x.* FROM (SELECT 
TITLE ,
LENGTH,
CASE 
WHEN LENGTH >0 AND LENGTH<50 THEN 'short'
WHEN LENGTH >50 AND LENGTH<100 THEN 'medium'
WHEN LENGTH>100 THEN 'long'
END
FROM FILM 
ORDER BY TITLE) AS x
dvdrental-# WHERE x.case LIKE 'short';
